#!/bin/bash

echo "Setting up Vercel environment variables for StarterPackApp"
echo "=========================================================="
echo ""
echo "Please run the following commands to set the required environment variables:"
echo ""
echo "# Railway API URL (REQUIRED)"
echo "npx vercel env add RAILWAY_API_URL production"
echo "Value: https://real-estate-app-production-ba5c.up.railway.app"
echo ""
echo "# Internal API Key (REQUIRED for Railway communication)"
echo "npx vercel env add INTERNAL_API_KEY production"
echo "Value: [Generate a secure random string, e.g., using: openssl rand -base64 32]"
echo ""
echo "# Other required environment variables:"
echo "npx vercel env add FIREBASE_ADMIN_PROJECT_ID production"
echo "npx vercel env add FIREBASE_ADMIN_CLIENT_EMAIL production"
echo "npx vercel env add FIREBASE_ADMIN_PRIVATE_KEY production"
echo ""
echo "After setting these, redeploy with:"
echo "npx vercel --prod"
echo ""
echo "To verify environment variables are set:"
echo "npx vercel env ls"